### ISSUE TITLE
Dump Format invalid

### ISSUE THREAD

**Issue by plutocrat** [mxgross/EasyBackupBundle#22]
Hi,
The dump as produced on an Ubuntu 18 server contained the line 
"mysqldump: [Warning] Using a password on the command line interface can be insecure."
At the top of the file, which means that when you try to restore it, it fails with a format error. Removing the line makes restoring the database possible. 

Suggestion: An automated restore from the web interface would be useful. Or at least, instructions on how to extract and restore a database from a dump.

**Comment by plutocrat** [comment]
Also, stray .env file left in backup directory by extracting a backup, was listed as a backup called .env. Should probably limit listing to *.zip

**Comment by mxgross** [comment]
Hello,
as long as there is no restore functionality, use this instruction: https://www.kimai.org/documentation/backups.html
In the chapter "restore" is everything descriped.

**Comment by mxgross** [comment]
Hello @plutocrat,
I fixed the detection for zip files in the dev branch and will be merged to master soon.

For the problem with the mysqldump warning you could do me a favor and test if the warning disappears when you add this in the file kimai2\var\plugins\EasyBackupBundle\Controller\EasyBackupController.php
![mysqldump_warning_prevention](https://user-images.githubusercontent.com/3718449/97787408-42932400-1bb2-11eb-8bbd-826eccdb86cf.jpg)
I cannot test it myself at the moment because it does not appear in my environment.

Please tell me if this will help.
Thanks,
Max
