### ISSUE TITLE
Backup error

### ISSUE THREAD

**Issue by stramag** [mxgross/EasyBackupBundle#55]
Hi,

Please can somebody help in my case,
I have installed this plugin without any error, but when I try to make a backup I got the following error:
Attempted to call an undefined method named "flashError" of class "KimaiPlugin\EasyBackupBundle\Service\EasyBackupService".

Please somebody can help me?

Best Regards,
GáborS

**Comment by mxgross** [comment]
Hi,
please have a look in the "Latest log" area on the EasyBackup main page.
There are some flashError calls inside the EasyBackupService where they don't belong to.
But because you receive that error it means there is something else wrong in the first place.
The easybackup.log or "Latest log" textbox shoud give you a hint.

If it does not help you, you can post the result here. Make sure to remove any sensitive data from the log before you upload or post it.

**Comment by stramag** [comment]
Hi,

Thank you for your answer and your help,
I figure out what is the main issue, the DB dump is failed because the reload privileges is missing. :-)

I granted and voala it is working! :-)

I appreciate your help!

BR,
GáborS

**Comment by stramag** [comment]
This is the command what i used:
GRANT RELOAD ON *.* TO 'kimai2'@'localhost';
