### ISSUE TITLE
Backups are empty / don't show up in EasyBackup screen

### ISSUE THREAD

**Issue by hyssop** [mxgross/EasyBackupBundle#57]
I have Kimai 2.0.22 setup and running fine (no added data yet), I added EasyBackup and the screen loads and runs backup without error, but nothing shows up in the list (json file is empty and the nothing else in the backup folder). 

Status check is all greeen.

Log:
[2023-05-21 01:59:00] INFO: --- S T A R T   C R E A T I N G   B A C K U P ---
[2023-05-21 01:59:00] INFO: Creating backup dir '/home/site/time2.site.com/kimai/var/easy_backup/2023-05-21_015900/'.
[2023-05-21 01:59:00] INFO: Creating manifest file '/home/site/time2.site.com/kimai/var/easy_backup/2023-05-21_015900/manifest.json'.

No PHP errors in error log.

**Comment by mxgross** [comment]
Hi @hyssop ,

isn't there any more content in your easybackup.log?
What is the content of the manifest.json?

Maybe you could upgrade to Kimai2 >2.0 and use the newest version of my plugin.

**Comment by hyssop** [comment]
Thank you for replying! (I was afraid the project was abandoned - which would be a bummer!)

var/easy_backup/easybackup.log only contains an entry for the last backup run (example above), it replaces rather than appending data.

A new backup folder (ex: var/easy_backup/2023-08-22_135311/) is created each time it is run from Kimai, and an empty manifest.json file is created.

I see no errors anywhere that I have looked (Kimai doctor, Easy Backup status, PHP error log).

I am running Kimai 2.0.22 and Easy Backup 2.0.0. 

I expected to find a permissions problem error somewhere, but have not so far.

Please tell me what else I can do.

**Comment by mxgross** [comment]
Strange that it can create the manifest.json file, but not write into it.
Maybe it is because of the git command. Can you try to execute this command in you servers terminal and give me the result:
```shell
git rev-parse HEAD
``` 
It should give you a git commit hash e.g. something like '9e7dceb29a10fda7e325fb2a0b4f30f227e27bd2'.

I also just pushed a new version at the main branch where I optimized the error handling when executing this command.

If it is a file permission problem you can try executing this again:
```shell
sudo chown -R :www-data . &&
sudo chmod -R g+r . &&
sudo chmod -R g+rw var/ &&
sudo chmod -R g+rw public/avatars/ &&
sudo chmod -R o+rw var/plugins/EasyBackupBundle
```
